image:
  - Visual Studio 2022
  - Ubuntu
  - MacOS

version: 6.0.0-preview-10-{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run -v:minimal -c:Release -p:LatestSupportedNet=net7.0 -f:net7.0 --project test/DryIoc.TestRunner/DryIoc.TestRunner.csproj
  - dotnet run -v:minimal -c:Release -p:LatestSupportedNet=net7.0 -f:net7.0 -p:UseCompilationOnly=true --project test/DryIoc.TestRunner/DryIoc.TestRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build.bat net8.0

    artifacts:
      - path: .\.dist\packages\*.nupkg
