image:
  - Visual Studio 2022
  - Ubuntu

version: 6.0.0-preview-07-{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run -v:minimal -p:DevMode=false -f:net7.0 -c:Release --project test/DryIoc.TestRunner/DryIoc.TestRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
